services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000   # automatic server startup
    volumes:
      - .:/app
    ports:
      - "8080:8000"                                   # external port 8080 -> 8000 in container
    env_file:
      - .env
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=onlinelibrary
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"                                   # external port 5433 -> 5432 in container

volumes:
  postgres_data:
