version: "3.9"

services:
  web:
    build: .
    command: sleep infinity          # container works without exit
    volumes:
      - .:/app
    ports:
      - "8080:8000"
    env_file:
      - .env
    depends_on:
      - db
    stdin_open: true                 # for interactive
    tty: true                        # for terminal

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=onlinelibrary
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"

volumes:
  postgres_data:
